ACCOUNTS = [ "GBJTZHVAZBBOLGJQ5NHO2NNQKVK5VLJTSJOGQGU64BCEHLSS4V3K7YNP", "GA6PLM43TPTJLPCCW5YX3VH6U43JKCFTDETPDZVHCMOHOTV23EOIFIFO", "GB74VPYD2LX35DW3WCABQEWGUJLMPEI26Y6LB3DMG7PPPCA43BPINZQW" ]
VERSION = "0.1.0"
SIGNING_KEY="GCHYC3WSZIG6T6PTP2H2BGN67W6AXD5GMKO7U5DPHCLGR3LMOSTY3F5V"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

[[PRINCIPALS]]
name = "Fifo Zatti"
email = "fifo@ahalabs.dev"
keybase = "fazzatti"
github = "https://www.github.com/fazzatti"

[DOCUMENTATION]
ORG_NAME = "Fifo Wallet Demo"
ORG_URL = "https://stellar.org"
ORG_DESCRIPTION = "demo wallet client."
